services:
  - type: web
    name: managed-care-dashboard
    runtime: docker
    plan: free
    healthCheckPath: /
    healthCheckProtocol: HTTP
    ports:
      - port: 8001
        protocol: HTTP
    envVars:
      - key: TRINO_HOST
        sync: false
      - key: TRINO_PORT
        sync: false
      - key: TRINO_USERNAME
        sync: false
      - key: TRINO_PASSWORD
        sync: false
      - key: TRINO_CATALOG
        sync: false
      - key: TRINO_SCHEMA
        sync: false
