import type { ActivityMeta, ActivityDomain } from '../types';

export const ACTIVITY_META: Record<string, ActivityMeta> = {
  daily_step_count: {
    activityType: 'daily_step_count',
    domain: 'STEPS' as ActivityDomain,
    isClinical: false,
    isEvergreen: true,
    defaultPoints: 0,
    benefitGatePoints: 0,
    intent: 'Walk enough steps to meet daily target',
    completionLogic: 'Wearable: auto-sync at 11:59 PM, stepsLogged >= target. Manual: log steps via input. Target starts 8000, +500 every 30 days. Partial -> ATTEMPTED.',
    minDurationSeconds: 0,
  },
  daily_mood_check: {
    activityType: 'daily_mood_check',
    domain: 'EVERGREEN' as ActivityDomain,
    isClinical: false,
    isEvergreen: true,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Log mood score for the day',
    completionLogic: 'Select emoji or score 1-5. Any selection -> COMPLETED + 1 pt. One submission per day.',
  },
  water_intake_log: {
    activityType: 'water_intake_log',
    domain: 'EVERGREEN' as ActivityDomain,
    isClinical: false,
    isEvergreen: true,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Log glasses of water consumed today',
    completionLogic: 'Tap [+] on water progress bar or reply with number. Logging any amount -> COMPLETED + 1 pt. Evening nudge at 6 PM if < 6 glasses.',
  },
  smart_insight_of_the_day: {
    activityType: 'smart_insight_of_the_day',
    domain: 'EVERGREEN' as ActivityDomain,
    isClinical: false,
    isEvergreen: true,
    defaultPoints: 0,
    benefitGatePoints: 0,
    intent: 'Read today\'s personalized health insight',
    completionLogic: 'Passive delivery. Auto-completed on open. No points.',
  },
  diet_plan_reminder: {
    activityType: 'diet_plan_reminder',
    domain: 'EVERGREEN' as ActivityDomain,
    isClinical: false,
    isEvergreen: true,
    defaultPoints: 0,
    benefitGatePoints: 0,
    intent: 'Follow your personalized diet plan today',
    completionLogic: 'Passive reminder. Auto-completed. No points.',
  },
  habit_guide_challenge: {
    activityType: 'habit_guide_challenge',
    domain: 'EVERGREEN' as ActivityDomain,
    isClinical: false,
    isEvergreen: true,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Complete today\'s habit building challenge',
    completionLogic: 'Tap [Done] after completing the described micro-habit. -> COMPLETED + 1 pt.',
  },
  mental_wellness_guided_session: {
    activityType: 'mental_wellness_guided_session',
    domain: 'MENTAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Complete a full guided wellness session',
    completionLogic: 'Timer-based session (min 10 min, RESILIENT 5 min). >= 90% duration -> COMPLETED + 2 pts. < 50% -> ATTEMPTED.',
    minDurationSeconds: 600,
  },
  meal_log_full_day: {
    activityType: 'meal_log_full_day',
    domain: 'DIET' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 6,
    benefitGatePoints: 0,
    intent: 'Log all three meals with photo or description',
    completionLogic: 'Log >= 2 of 3 meals (Breakfast/Lunch/Dinner). Each meal +2 pts. COMPLETED at 2+ meals.',
  },
  diet_food_swap_challenge: {
    activityType: 'diet_food_swap_challenge',
    domain: 'DIET' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 3,
    benefitGatePoints: 0,
    intent: 'Replace one specified food with the dietician-suggested alternative',
    completionLogic: 'Tap [I made the swap] + free-text description (min 1 sentence). -> COMPLETED + 3 pts.',
  },
  diet_meal_timing_log: {
    activityType: 'diet_meal_timing_log',
    domain: 'DIET' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Log the time of first meal today',
    completionLogic: 'Time picker input -> Submit -> COMPLETED + 1 pt. Trend shown vs last week.',
  },
  diet_hydration_focus_day: {
    activityType: 'diet_hydration_focus_day',
    domain: 'DIET' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Log reaching 10-glass hydration target',
    completionLogic: 'Water log must reach 10 glasses. At 10 -> COMPLETED + 2 pts.',
  },
  diet_food_mood_journal: {
    activityType: 'diet_food_mood_journal',
    domain: 'DIET' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Complete 3-question food-mood reflection',
    completionLogic: '3 questions answered -> COMPLETED + 2 pts.',
  },
  diet_rainbow_challenge: {
    activityType: 'diet_rainbow_challenge',
    domain: 'DIET' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Log eating 4+ different coloured vegetables/fruits',
    completionLogic: 'Tap >= 4 colours from grid -> COMPLETED + 2 pts. 3 colours -> ATTEMPTED + 1 pt.',
  },
  diet_gut_health_day: {
    activityType: 'diet_gut_health_day',
    domain: 'DIET' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Consume and log one probiotic food today',
    completionLogic: 'Select probiotic food from list or type custom -> Submit -> COMPLETED + 2 pts.',
  },
  diet_calorie_audit_day: {
    activityType: 'diet_calorie_audit_day',
    domain: 'DIET' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Review and audit today\'s calorie intake',
    completionLogic: 'Log all meals with calories. Review summary -> COMPLETED + 2 pts.',
  },
  diet_dietician_challenge: {
    activityType: 'diet_dietician_challenge',
    domain: 'DIET' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 3,
    benefitGatePoints: 0,
    intent: 'Complete today\'s dietician-assigned challenge',
    completionLogic: 'Contextual 7-day window around dietician consult. Complete challenge + confirm -> COMPLETED + 3 pts.',
  },
  diet_weekly_dietician_review: {
    activityType: 'diet_weekly_dietician_review',
    domain: 'DIET' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Review diet progress with your dietician plan',
    completionLogic: 'Fires day after dietician consult. Read review + acknowledge -> COMPLETED + 2 pts.',
  },
  weekly_step_challenge: {
    activityType: 'weekly_step_challenge',
    domain: 'STEPS' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 10,
    benefitGatePoints: 0,
    intent: 'Set step goal for the week and track completion',
    completionLogic: 'Monday: Tap [Join Challenge]. 7-day window. >= 5/7 days met daily target -> COMPLETED + 10 bonus pts.',
  },
  step_burst_challenge: {
    activityType: 'step_burst_challenge',
    domain: 'STEPS' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 3,
    benefitGatePoints: 0,
    intent: 'Walk 2,000 steps in 15 minutes',
    completionLogic: '[Start Burst Timer] -> 15-min countdown. Wearable: auto-verify >= 1800 steps. Manual: trust-based confirm -> COMPLETED + 3 pts.',
    minDurationSeconds: 900,
  },
  post_meal_walk_prompt: {
    activityType: 'post_meal_walk_prompt',
    domain: 'STEPS' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Walk for 10 minutes after a meal',
    completionLogic: '[Start 10-min Timer] -> timer runs -> [Mark Done] -> COMPLETED + 2 pts. Or wearable >= 1000 steps in 15 min post-meal.',
    minDurationSeconds: 600,
  },
  active_hour_challenge: {
    activityType: 'active_hour_challenge',
    domain: 'STEPS' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 5,
    benefitGatePoints: 0,
    intent: 'Complete 1 hour of active movement this weekend',
    completionLogic: '[Start 60-min Timer]. Check-ins at 20/40/60 min. All completed -> COMPLETED + 5 pts.',
    minDurationSeconds: 3600,
  },
  stair_challenge: {
    activityType: 'stair_challenge',
    domain: 'STEPS' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Use stairs instead of elevator today',
    completionLogic: 'Confirm [I took stairs today] -> COMPLETED + 2 pts.',
  },
  active_commute_day: {
    activityType: 'active_commute_day',
    domain: 'STEPS' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Walk or cycle part of your commute today',
    completionLogic: 'Confirm active commute or log commute steps -> COMPLETED + 2 pts.',
  },
  nature_walk_prompt: {
    activityType: 'nature_walk_prompt',
    domain: 'STEPS' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Take a 20-minute walk in nature or a park',
    completionLogic: 'Tap [Start Walk] timer. 20 min -> [Mark Complete] -> COMPLETED + 2 pts.',
  },
  move_every_hour_challenge: {
    activityType: 'move_every_hour_challenge',
    domain: 'STEPS' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 3,
    benefitGatePoints: 0,
    intent: 'Move for 5 minutes every hour today',
    completionLogic: 'Check off each hourly movement (min 6 check-ins) -> COMPLETED + 3 pts.',
  },
  stress_journal: {
    activityType: 'stress_journal',
    domain: 'MENTAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Write a short journal entry about today\'s stress',
    completionLogic: 'Text area min 50 characters -> Submit -> COMPLETED + 2 pts.',
  },
  gratitude_check_in: {
    activityType: 'gratitude_check_in',
    domain: 'MENTAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Write one or more things you are grateful for',
    completionLogic: 'Free text min 20 characters -> Submit -> COMPLETED + 1 pt.',
  },
  sleep_quality_log: {
    activityType: 'sleep_quality_log',
    domain: 'MENTAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Log last night\'s sleep hours and quality',
    completionLogic: 'Sleep duration (0-12h) + quality (1-5 stars). Both submitted -> COMPLETED + 1 pt.',
  },
  sleep_hygiene_audit: {
    activityType: 'sleep_hygiene_audit',
    domain: 'MENTAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Complete a sleep hygiene self-assessment',
    completionLogic: 'Answer all audit questions -> COMPLETED + 2 pts.',
  },
  digital_detox_nudge: {
    activityType: 'digital_detox_nudge',
    domain: 'MENTAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Spend 30 minutes without screens this evening',
    completionLogic: 'Confirm [I did my digital detox] -> COMPLETED + 1 pt.',
  },
  social_wellness_prompt: {
    activityType: 'social_wellness_prompt',
    domain: 'MENTAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Connect with a friend or family member today',
    completionLogic: 'Confirm meaningful social connection -> COMPLETED + 1 pt.',
  },
  mental_health_education_bite: {
    activityType: 'mental_health_education_bite',
    domain: 'MENTAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Read a short mental health education article',
    completionLogic: 'Min read time enforced. [Got it] button appears after time. Click -> COMPLETED + 2 pts.',
  },
  emotional_eating_check: {
    activityType: 'emotional_eating_check',
    domain: 'MENTAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Reflect on emotional eating patterns today',
    completionLogic: '2-question check answered -> COMPLETED + 1 pt.',
  },
  body_scan_awareness: {
    activityType: 'body_scan_awareness',
    domain: 'MENTAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Complete a 5-minute body scan awareness exercise',
    completionLogic: 'Timed 5-min guided body scan. Completion -> COMPLETED + 2 pts.',
    minDurationSeconds: 300,
  },
  mindfulness_moment: {
    activityType: 'mindfulness_moment',
    domain: 'MENTAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Take a 3-minute mindfulness pause',
    completionLogic: 'Timed 3-min guided pause. Completion -> COMPLETED + 2 pts.',
    minDurationSeconds: 180,
  },
  joy_activity_prompt: {
    activityType: 'joy_activity_prompt',
    domain: 'MENTAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Do one joyful activity today',
    completionLogic: 'Confirm joy activity completion -> COMPLETED + 1 pt.',
  },
  hra_energy_tracker: {
    activityType: 'hra_energy_tracker',
    domain: 'HRA' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Rate energy level and identify primary cause',
    completionLogic: 'Slider 1-10 + dropdown (Sleep/Diet/Exercise/Stress/Other). Both answered -> COMPLETED + 1 pt.',
  },
  hra_periodic_checkin: {
    activityType: 'hra_periodic_checkin',
    domain: 'HRA' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Complete the periodic health re-assessment',
    completionLogic: 'All HRA questions answered -> COMPLETED + 2 pts. Re-scores engagement and re-evaluates persona.',
  },
  hra_weekly_symptom_check: {
    activityType: 'hra_weekly_symptom_check',
    domain: 'HRA' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Log any new or worsening symptoms this week',
    completionLogic: 'Symptom checklist + severity. Submitted -> COMPLETED + 1 pt.',
  },
  hra_lifestyle_self_assessment: {
    activityType: 'hra_lifestyle_self_assessment',
    domain: 'HRA' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Complete lifestyle self-assessment',
    completionLogic: 'All lifestyle questions answered -> COMPLETED + 2 pts.',
  },
  hra_vitals_awareness_check: {
    activityType: 'hra_vitals_awareness_check',
    domain: 'HRA' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Answer vitals awareness questions',
    completionLogic: 'All questions answered -> COMPLETED + 2 pts.',
  },
  hra_disease_risk_quiz: {
    activityType: 'hra_disease_risk_quiz',
    domain: 'HRA' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Complete a disease risk awareness quiz',
    completionLogic: 'All quiz questions answered -> COMPLETED + 2 pts.',
  },
  hra_sleep_hygiene_audit: {
    activityType: 'hra_sleep_hygiene_audit',
    domain: 'HRA' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Complete a sleep hygiene audit via HRA',
    completionLogic: 'All audit questions answered -> COMPLETED + 2 pts.',
  },
  hra_body_measurement_log: {
    activityType: 'hra_body_measurement_log',
    domain: 'HRA' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Log body measurements (waist, hip)',
    completionLogic: 'Submit measurements -> COMPLETED + 1 pt.',
  },
  hra_medication_side_effect_log: {
    activityType: 'hra_medication_side_effect_log',
    domain: 'HRA' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Log any medication side effects experienced',
    completionLogic: 'Side effect checklist submitted -> COMPLETED + 1 pt.',
  },
  circle_of_care_weekly_share: {
    activityType: 'circle_of_care_weekly_share',
    domain: 'COC' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 3,
    benefitGatePoints: 0,
    intent: 'Share weekly health summary with family/support circle',
    completionLogic: 'Auto-generated summary. Review + [Confirm & Share] -> mock WhatsApp send -> COMPLETED + 3 pts.',
  },
  circle_of_care_milestone_share: {
    activityType: 'circle_of_care_milestone_share',
    domain: 'COC' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 5,
    benefitGatePoints: 0,
    intent: 'Share a health milestone with your care circle',
    completionLogic: 'Milestone message generated. Confirm share -> COMPLETED + 5 pts.',
  },
  circle_of_care_family_meal_challenge: {
    activityType: 'circle_of_care_family_meal_challenge',
    domain: 'COC' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 3,
    benefitGatePoints: 0,
    intent: 'Invite family to do a healthy meal challenge',
    completionLogic: 'Send challenge invite + confirm family participation -> COMPLETED + 3 pts.',
  },
  circle_of_care_caregiver_guide: {
    activityType: 'circle_of_care_caregiver_guide',
    domain: 'COC' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Share caregiver guide with a family member',
    completionLogic: 'Guide shared via mock WhatsApp -> COMPLETED + 2 pts.',
  },
  circle_of_care_checkin_call: {
    activityType: 'circle_of_care_checkin_call',
    domain: 'COC' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 3,
    benefitGatePoints: 0,
    intent: 'Schedule or complete a check-in call with your care circle',
    completionLogic: 'Call scheduled or completed -> COMPLETED + 3 pts.',
  },
  circle_of_care_shared_goal: {
    activityType: 'circle_of_care_shared_goal',
    domain: 'COC' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Set a shared health goal with a family member',
    completionLogic: 'Shared goal set and confirmed -> COMPLETED + 2 pts.',
  },
  circle_of_care_ask_for_support: {
    activityType: 'circle_of_care_ask_for_support',
    domain: 'COC' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Ask a family member for health support today',
    completionLogic: 'Support request sent -> COMPLETED + 2 pts.',
  },
  circle_of_care_appreciation_note: {
    activityType: 'circle_of_care_appreciation_note',
    domain: 'COC' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Send an appreciation note to your care circle',
    completionLogic: 'Note written and sent -> COMPLETED + 2 pts.',
  },
  weekly_weigh_in: {
    activityType: 'weekly_weigh_in',
    domain: 'WEIGHT' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Log current weight',
    completionLogic: 'Weight input (kg) -> Submit -> COMPLETED + 2 pts. Trend shown. Smart scale: auto-populate.',
  },
  waist_measurement_monthly: {
    activityType: 'waist_measurement_monthly',
    domain: 'WEIGHT' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Measure and log waist circumference',
    completionLogic: 'Waist measurement (cm) submitted -> COMPLETED + 2 pts.',
  },
  weight_trend_review: {
    activityType: 'weight_trend_review',
    domain: 'WEIGHT' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Review your weight trend over the past 2 weeks',
    completionLogic: 'View trend chart + acknowledge -> COMPLETED + 1 pt.',
  },
  portion_plate_challenge: {
    activityType: 'portion_plate_challenge',
    domain: 'WEIGHT' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Use portion plate method for one meal today',
    completionLogic: 'Log meal with portion method description -> COMPLETED + 2 pts.',
  },
  bmi_awareness_check: {
    activityType: 'bmi_awareness_check',
    domain: 'WEIGHT' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Review your current BMI and target',
    completionLogic: 'View BMI card + acknowledge -> COMPLETED + 1 pt.',
  },
  sodium_sugar_awareness_day: {
    activityType: 'sodium_sugar_awareness_day',
    domain: 'WEIGHT' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Track and reduce sodium/sugar intake today',
    completionLogic: 'Log meals with sodium/sugar awareness -> COMPLETED + 2 pts.',
  },
  no_scale_body_check: {
    activityType: 'no_scale_body_check',
    domain: 'WEIGHT' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Note non-scale body changes this month',
    completionLogic: 'Free text reflection on body changes -> COMPLETED + 1 pt.',
  },
  visceral_fat_awareness: {
    activityType: 'visceral_fat_awareness',
    domain: 'WEIGHT' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Learn about visceral fat and your risk factors',
    completionLogic: 'Read education card + acknowledge -> COMPLETED + 2 pts.',
  },
  mindful_eating_day: {
    activityType: 'mindful_eating_day',
    domain: 'WEIGHT' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Practice mindful eating at all meals today',
    completionLogic: 'Confirm mindful eating practice at end of day -> COMPLETED + 2 pts.',
  },
  binah_face_scan: {
    activityType: 'binah_face_scan',
    domain: 'CLINICAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 50,
    intent: 'Complete a Binah AI face scan',
    completionLogic: 'Camera scan 60 sec. Results: HR, SpO2, stress. Scan completes -> COMPLETED + 2 pts.',
    requiresBenefit: 'binah',
    minDurationSeconds: 60,
  },
  glucometer_reading_log: {
    activityType: 'glucometer_reading_log',
    domain: 'CLINICAL' as ActivityDomain,
    isClinical: true,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 250,
    intent: 'Log blood glucose reading from glucometer',
    completionLogic: 'Value input (mg/dL) -> Submit -> COMPLETED + 1 pt. If > 200 -> CRITICAL_ALERT.',
    requiresBenefit: 'glucometer',
  },
  smart_scale_reading_log: {
    activityType: 'smart_scale_reading_log',
    domain: 'CLINICAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 1,
    benefitGatePoints: 250,
    intent: 'Sync smart scale reading',
    completionLogic: 'Auto-populated when patient steps on scale. Manual entry fallback -> COMPLETED + 1 pt.',
    requiresBenefit: 'smart_scale',
  },
  wearable_steps_sync: {
    activityType: 'wearable_steps_sync',
    domain: 'EVERGREEN' as ActivityDomain,
    isClinical: false,
    isEvergreen: true,
    defaultPoints: 0,
    benefitGatePoints: 0,
    intent: 'Sync steps from wearable device',
    completionLogic: 'Auto-sync from wearable. No action needed.',
    requiresBenefit: 'wearable',
  },
  wearable_hrv_sync: {
    activityType: 'wearable_hrv_sync',
    domain: 'EVERGREEN' as ActivityDomain,
    isClinical: false,
    isEvergreen: true,
    defaultPoints: 1,
    benefitGatePoints: 0,
    intent: 'Sync HRV data from wearable',
    completionLogic: 'Auto-sync from wearable Monday. -> COMPLETED + 1 pt.',
    requiresBenefit: 'wearable',
  },
  gym_session_cardio: {
    activityType: 'gym_session_cardio',
    domain: 'STEPS' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 3,
    benefitGatePoints: 300,
    intent: 'Complete a cardio gym session',
    completionLogic: 'Check off >= 80% of exercises in program. >= 15 min -> COMPLETED + 3 pts.',
  },
  gym_session_strength: {
    activityType: 'gym_session_strength',
    domain: 'STEPS' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 3,
    benefitGatePoints: 300,
    intent: 'Complete a strength training gym session',
    completionLogic: 'Check off >= 80% of exercises. >= 15 min -> COMPLETED + 3 pts.',
  },
  gym_session_yoga: {
    activityType: 'gym_session_yoga',
    domain: 'STEPS' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 3,
    benefitGatePoints: 300,
    intent: 'Complete a yoga gym session',
    completionLogic: 'Check off >= 80% of poses/exercises. >= 15 min -> COMPLETED + 3 pts.',
  },
  disease_education_module: {
    activityType: 'disease_education_module',
    domain: 'HRA' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 0,
    intent: 'Read and acknowledge an education module',
    completionLogic: 'Min read time enforced. [Got it] appears after time. Click -> COMPLETED + 2 pts.',
  },
  diabetes_ai_glucose_pattern_review: {
    activityType: 'diabetes_ai_glucose_pattern_review',
    domain: 'CLINICAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 200,
    intent: 'Review AI-generated glucose pattern analysis',
    completionLogic: 'View AI analysis + acknowledge -> COMPLETED + 2 pts. Requires HIGH/VERY_HIGH cohort.',
  },
  diabetes_ai_weekly_report: {
    activityType: 'diabetes_ai_weekly_report',
    domain: 'CLINICAL' as ActivityDomain,
    isClinical: false,
    isEvergreen: false,
    defaultPoints: 2,
    benefitGatePoints: 200,
    intent: 'Review weekly AI diabetes management report',
    completionLogic: 'View weekly report + acknowledge -> COMPLETED + 2 pts.',
  },
};
